"""rename address to location column

Revision ID: 76a93a69a378
Revises: 2b7372928122
Create Date: 2024-04-02 17:46:01.598881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a93a69a378'
down_revision = '2b7372928122'
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('location', sa.String(), nullable=False))
    # op.drop_column('departments', 'address')
    # # ### end Alembic commands ###
    op.alter_column('departments', 'address',  new_column_name='location')


def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    # op.drop_column('departments', 'location')
    # # ### end Alembic commands ###
    op.alter_column('departments', 'location',  new_column_name='address')
